### ISSUE TITLE
你好，我们现在有个安卓工业平板，上面没有串口，只有USB口，请问可以通过USB转串口线进行串口通信吗？

### ISSUE THREAD

**Issue by scholar-yan** [HelloHuDi/usb-with-serial-port#1]
我们安卓工业平板设备要外接地秤，地秤上是通过串口与安卓设备连接的，但是我们定制的安卓工业平板上没有串口，只有USB口，请问可以通过USB转串口线进行通信吗？我以前实现的是直接通过串口通信，现在改成USB口了，是不是代码也需要改，希望能够回答，刚接触到这一模块，有点模糊，谢谢。

**Comment by scholar-yan** [comment]
现在手头上也没设备，所以没法测试，只能先来问问。

**Comment by HelloHuDi** [comment]
可以实现通信，因为通信的方式不一样，代码也是需要改动的， 改动的部分也是在建立通信连接这块

**Comment by scholar-yan** [comment]
好的，谢谢

**Comment by scholar-yan** [comment]
我现在用的是usbSerialForAndroid这个库工程
