### ISSUE TITLE
v0.4.0扫描usb报错

### ISSUE THREAD

**Issue by iotxc** [HelloHuDi/usb-with-serial-port#10]
使用scanUsbPort()方法扫描usb时报错，在源码UsbSerialProber类的58行调用
new UsbExtendDriver().getExtendDrivers()时，因为没有初始化extendDrivers导致在UsbSerialProber中69行循环时而出现空指针问题。

**Comment by HelloHuDi** [comment]
确实存在这样的问题，是我的过失，你可以使用0.3.0版本来避免这个问题，这个问题我会在下个版本修复，感谢你的反馈

**Comment by iotxc** [comment]
好的， 辛苦

**Comment by iotxc** [comment]
好的， 辛苦
