### ISSUE TITLE
使用这个usb转串口库 数据发送出去，但是接收不到是怎么回事

### ISSUE THREAD

**Issue by Andjdd** [HelloHuDi/usb-with-serial-port#2]
DeviceMeasureController.INSTANCE.measure(port, new UsbMeasureParameter(UsbPortDeviceType.USB_FTD, 115200, 8, 1, 0), new UsbMeasureListener() {
            @Override
            public void measuring(UsbSerialPort usbSerialPort, byte[] data) {
                LogUtils.e("data》》》", data + "");//没有返回数据
                list.clear();
                if (type.equals("zw")) {
                    SerialDealData.DealZW(data);
                }
                       }

            @Override
            public void write(UsbSerialPort usbSerialPort) {
                //允许持续性写入数据
                try {
                    usbSerialPort.write(new byte[]{(byte) 0xff, (byte) 0xff}, 1000);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

            @Override
            public void measureError(String message) {

            }
        });
    }

**Comment by HelloHuDi** [comment]
你好，没有看到具体的情况，无法给出准确的判断，建议可以：
1.先判断设备是否正常工作，可以借助一些调试工具（android 或者 pc）来检测, 同时可以检测下发送的数据设备是否正常响应，推荐下 https://github.com/HelloHuDi/usbSerialPortTools；
2.若设备在正常工作，尝试使用DeviceMeasureController.INSTANCE.write()来发送数据，或者 上图返回的usbSerialPort来写入；
3.如工具库依旧无法正常工作，建议debug下是否有异常；

**Comment by Andjdd** [comment]
现在有数据返回了，问题存在：第一次安装应用进去数据没法接收到，貌似初始化没有成功或者跟usb权限打开有关系？退出应用在进去这次就可以正常的 返回数据了

**Comment by HelloHuDi** [comment]
若是权限的问题，应该会响应 measureError(), 可以尝试处理这个回调

**Comment by Andjdd** [comment]
权限回调你哪里有好的推荐嘛

**Comment by HelloHuDi** [comment]
常见的权限请求只能处理单个usb或者统一处理，我这里没有更好的推荐, 可以尝试改造 RequestUsbPermission 类自己处理

**Comment by Andjdd** [comment]
总之我都去试了 可能不怎么会使用，始终第一次进去不成功返回数据

**Comment by HelloHuDi** [comment]
有回调measureError()吗，可以观察下库的打印日志，init初始化打开log
