### ISSUE TITLE
ReadWriteRunnable异常nullpointer

### ISSUE THREAD

**Issue by bilifo** [HelloHuDi/usb-with-serial-port#3]
发出去了,但始终无接收的数据,debug时,追踪到ReadWriteRunnable类的override fun run()方法,由reading()抛出异常,不是很理解该异常到底是什么出错抛出.
依赖版本:implementation 'com.hd:usbserialport:0.2.4'

**Comment by HelloHuDi** [comment]
你好，你是操作的usb还是串口呢？ 有没有详细的日志，方便的话可以优先尝试 https://github.com/HelloHuDi/usbSerialPortTools 这个工具判断，或者找其他调试工具判断设备是否正常

**Comment by bilifo** [comment]
是usb转虚拟串口时出现的问题.
我当时的场景是使用一个条码扫描模块,不知道是由于平台限制还是其他什么原因,对应的dev/ttyACM设备,并不是一直保持存在,在扫码模块发回信息时,会先卸载已有的ttyACM设备,再重新挂载ttyACM.而数据也就没有回传成功.
我使用了作者你的那个工具,发现通过选串口的能成功获得回传数据,而选usb转串口的不行.所以我接下来会使用直接串口的方式再试试,但我不明白,明明就是usb转串口的设备,为什么反倒还不行,而直接串口倒是能成功

**Comment by HelloHuDi** [comment]
涉及到设备调试情况比较复杂，给出个人的一点建议：
1.dev/ttyACM这个串口地址时有时无，首先确认这是不是目标地址，然后在排查接触不良的情况；
2.在Android平台上我所接触的usb转串口是设备本身是串口然后转化成usb（win下不分usb，这应该是系统及芯片决定的，当然这是我个人的观点），然后根据对应转化的usb协议通信，现在你usb通信方式不成功而串口方式可以，先确认协议有没有选对，在检查转化有没有成功

希望对你有所帮助

**Comment by bilifo** [comment]
谢谢你的回复
硬件这些都检查过了,排除了接触不良.
扫描器本身出来的线是usb,但我们安卓平台这边是要把它转换成串口来获取数据.
使用是
DeviceMeasureController.INSTANCE.measure(port, new UsbMeasureParameter(UsbPortDeviceType.USB_CDC_ACM, 115200, 8, 1, 0), new UsbMeasureListener() {
这样写的,不知道是否正确

**Comment by HelloHuDi** [comment]
既然是串口，那应当用串口的通信方式， 传递 SerialPortMeasureParameter 作为参数

**Comment by bilifo** [comment]
好的,谢谢,我使用串口方式成功了

**Comment by bilifo** [comment]
HelloHuDi
我建议在README的说明中,
             @Override
             public void measuring(UsbSerialPort usbSerialPort, byte[] data) {
             }
稍微修改为
 @Override
             public void measuring(UsbSerialPort usbSerialPort, byte[] data) {
                 try{
                    //添加你对返回数据的处理
                 catch (Exception e){
                   e.printStackTrace();
                  }
             }
这样能让像我一样的新手使用者,能区分是自己处理逻辑问题引起的测量失败
