### ISSUE TITLE
串口数据接收问题

### ISSUE THREAD

**Issue by iotxc** [HelloHuDi/usb-with-serial-port#4]
博主，你好， 在使用你的lib时出现一些疑惑，希望你能解答一下。
在使用CP2102进行透传测试时发现：
DeviceMeasureController.INSTANCE.measure(port, new UsbMeasureParameter(115200,8,1,0), new UsbMeasureListener() {
            @Override
            public void measuring(UsbSerialPort usbSerialPort, byte[] data) {
                //处理返回数据
            }

            @Override
            public void write(UsbSerialPort usbSerialPort) {
            }
            @Override
            public void measureError(String message) {
            }
        });
这里接收到的数据总是一个字符一个字符的。比如我发送的是：ABCD字符串，我接收的时候这个measuring(UsbSerialPort usbSerialPort, byte[] data){}是会被调用4次的也就是A、B、C、D是依次返回，并不是一下返回ABCD。
不知道我这么说你是否理解， 还望回复

**Comment by HelloHuDi** [comment]
你好，查看源码ReadWriteRunnable你会发现这是个死循环，一旦读取到数据就会马上响应，现在一次只读取到一个字节，这说明设备回复到也是一个字节一个字节回复的，从性能上考虑，这个地方反复回调，确实回有性能上的消耗，但这已经不属于软件层可以解决的了，当然你可以调整源码ReadWriteRunnable让他等待几毫秒，不过我不建议这么做！那还有一种方式，在measuring回调中，你监测这个数据，达到预期就继续响应

**Comment by bilifo** [comment]
这个我也遇到了,不过我是用一个暂存数组,来先存放收到数据,当出现下一个数据的帧头时,把暂存数据作为一个完整数据输出

**Comment by githubxc** [comment]
谢谢， 已经解决了， 是发送数据时有问题。

**Comment by iotxc** [comment]
@HelloHuDi @bilifo 谢谢， 已经解决了， 是发送数据时有问题。
