### ISSUE TITLE
使用USB转串口通信,连接已经被成功打开,当此时将USB接口拔出,调用write方法会阻塞线程。

### ISSUE THREAD

**Issue by KotlinAmai** [HelloHuDi/usb-with-serial-port#5]
在Ch34xSerialDriver下的Ch340SerialPort 的write方法 中

amtWritten = mConnection.bulkTransfer 返回的 amtWritten ，在之后的判断 amtWritten<=0 时，没有抛出IOException 而是将 amtWritten 重置为了0。

offset += amtWritten; offset 一直为0；导致最上方的  while (offset < src.length) 一直成立。因此阻塞了线程。

**Comment by HelloHuDi** [comment]
好的 ，谢谢你的反馈

**Comment by KotlinAmai** [comment]
在其它的Driver类中，好像也有几个类有类似的问题。
