### ISSUE TITLE
接收几次之后就会回调measureError方法，返回"本次测量失败"

### ISSUE THREAD

**Issue by Leu-Z** [HelloHuDi/usb-with-serial-port#6]
发送串口数据的是一个体温枪，我使用usb转串口测量单个目标设备 ，接收几次串口数据之后，就回调会measureError方法，返回"本次测量失败"，然后就再也接收不到数据了。

我在A平板上测试没有出现这个问题，但是在B平板上测试出现了这个问题，貌似是连接成功后，过一会儿接收数据就会回调measureError方法。

但是我在B平板上使用你提供的测试工具APK，就不会出现这个情况，所以现在搞不清楚到底是哪里出了问题。

**Comment by bilifo** [comment]
貌似你这个问题可能是自己代码中的bug,你在
public void measuring(@NotNull String s, @NotNull byte[] bytes) {
                    try {
                       Log.e(TAG,"String : "+s+"  data:"+ Arrays.toString(bytes));
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
加上try catch,将你的代码包起来,看是否是自己代码的错误

**Comment by HelloHuDi** [comment]
你好，不知道你是否已经解决了问题，不过测试工具是不涉及任何业务逻辑的，注意查看打印的日志

**Comment by Leu-Z** [comment]
@bilifo @HelloHuDi 感谢，的确是我自己代码的问题。数据有时候是分两组发送过来，有时候又是分3组或者4组发送过来，但是总的数据量不变。之前没想到会这样，现在处理了一下，把数据累加起来到了固定量之后再处理就ok了。
