### ISSUE TITLE
关于单个串口关闭问题

### ISSUE THREAD

**Issue by bilifo** [HelloHuDi/usb-with-serial-port#7]
使用过程中发现,如果打开所有串口进行接收,cpu占用达到70%,而指定串口进行接收只占25%,这意味着串口开得越多,资源的占用越高,这对多串口应用,是比较糟糕的事,而且貌似没有单独关闭某个串口的方法

**Comment by HelloHuDi** [comment]
是的，开发的时候欠考虑了，后续我会考虑重新调整结构的
