### ISSUE TITLE
usb插拔 从走oncreate 问题导致activity退出

### ISSUE THREAD

**Issue by Andjdd** [HelloHuDi/usb-with-serial-port#8]
usb插拔 从走oncreate 问题导致activity退出

**Comment by Andjdd** [comment]
怎么解决大神

**Comment by HelloHuDi** [comment]
报什么错呢？看下日志

**Comment by Andjdd** [comment]
现在没有捕捉到错误信息

**Comment by HelloHuDi** [comment]
没有日志现在不好做判断，可以通过调试及log的方式跟踪下

**Comment by Andjdd** [comment]
你好 然后我app设置了开机自启功能，自启后发现没有进  usbSerial.OpenUsb()这个里面，这个在oncreate里面的

**Comment by Andjdd** [comment]
你好 每次重启设备 都会弹出usb权限提示框这个怎么解决的

**Comment by Andjdd** [comment]
Timeout of broadcast BroadcastRecord{ec9eb52 u0 android.hardware.usb.action.USB_DEVICE_ATTACHED} - receiver=android.os.BinderProxy@5185e23, started 10000ms ago

**Comment by HelloHuDi** [comment]
usb请求提示这个问题貌似只能从room入手，应用层暂时无法解决
